---
application:
  name: 'geurs21'
  project: 'first project'
  publicly_accessible: true
  organization: 'QoveryCommunity'
  start_timeout: 5m
routers:
  - name: 'main-geurs21'
    routes:
      - application_name: 'geurs21'
        paths:
          - '/'
